basic:
  clash_config_dir: /srv/mihomo
  clash_bin_path: /usr/bin/mihomo
  clash_config_path: /srv/mihomo/config.yaml
  timeout: null
service:
  clash_srv_name: mihomo
  is_user: false
extra:
  edit_cmd: ''
  open_dir_cmd: ''
